package com.susumonitor.server.module.auth.controller;

import com.susumonitor.server.common.ClientIpResolver;
import com.susumonitor.server.module.auth.dto.LoginRequest;
import com.susumonitor.server.module.auth.dto.RegisterRequest;
import com.susumonitor.server.module.auth.limit.LoginRateLimiter;
import com.susumonitor.server.module.auth.limit.RegisterRateLimiter;
import com.susumonitor.server.module.auth.service.UserService;
import com.susumonitor.server.module.auth.vo.CurrentUserVo;
import com.susumonitor.server.module.auth.vo.LoginVo;
import com.susumonitor.server.security.AuthenticatedUser;
import com.susumonitor.server.security.JwtAuthenticationFilter;
import com.susumonitor.server.security.JwtTokenService;
import com.susumonitor.server.security.RedisTokenBlacklist;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.validation.Valid;
import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.http.HttpHeaders;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * 认证控制器，提供用户注册、登录、获取当前用户信息和登出接口。
 *
 * <p>所有认证接口统一以 /api/auth 为路径前缀，通过 UserService 完成认证业务。</p>
 */
// 将认证接口归入 OpenAPI 文档的 auth 分组，与 openapi-auth.json 契约的 tag 一致。
@Tag(name = "auth", description = "Authentication and registration")
@Slf4j
@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
public class AuthController {

    private final UserService userService;

    private final ObjectProvider<RedisTokenBlacklist> tokenBlacklist;

    private final ObjectProvider<LoginRateLimiter> loginRateLimiter;

    private final ObjectProvider<RegisterRateLimiter> registerRateLimiter;

    private final ClientIpResolver clientIpResolver;

    private final Clock clock;

    /** 应用配置：读取 token-blacklist-on-error 故障语义开关（2026-09-14 决策一）。 */
    private final com.susumonitor.server.config.AppProperties appProperties;

    /**
     * 接收注册请求并委托 UserService 完成用户创建业务。
     *
     * <p>与登录一致按客户端 IP 做防滥用限流（超限 42905），
     * 防止批量注册淹没审核队列与数据库。</p>
     *
     * @param request 注册请求（触发 Bean Validation 校验）
     * @param httpRequest HTTP 请求（解析客户端 IP）
     * @return 当前用户公开信息
     */
    // 生成 OpenAPI 端点文档，summary/description/operationId 与 openapi-auth.json 的 registerUser 操作对齐。
    @Operation(
            summary = "Register user",
            description = "Registers a user. The first user becomes admin/approved; "
                    + "subsequent users become user/pending. X-Request-ID is generated by the server; "
                    + "a valid X-Correlation-ID is echoed in the response. "
                    + "A rate-limited client receives HTTP 429 with code 42905.",
            operationId = "registerUser")
    // 声明注册接口的错误响应（HTTP 状态 + 业务错误码），与契约 responses 对齐。
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "User registered"),
            @ApiResponse(responseCode = "400", description = "Invalid request parameter (40002)"),
            @ApiResponse(responseCode = "409", description = "Username already exists (40900)"),
            @ApiResponse(responseCode = "429",
                    description = "Registration rate limit exceeded (42905). "
                            + "Retry after the number of seconds in Retry-After.")
    })
    @PostMapping("/register")
    public com.susumonitor.server.common.ApiResponse<CurrentUserVo> register(
            @Valid
            @RequestBody RegisterRequest request,
            HttpServletRequest httpRequest) {
        RegisterRateLimiter limiter = registerRateLimiter.getIfAvailable();
        if (limiter != null) {
            limiter.checkAttempt(clientIpResolver.resolve(httpRequest));
        }
        return com.susumonitor.server.common.ApiResponse.success(userService.register(request));
    }

    /**
     * 校验用户凭据并为已审核用户签发 JWT。
     *
     * <p>登录前先做防爆破限流（按客户端 IP 固定窗口计数，超限 429）。
     * 限流实现由 Redis 启用状态决定：Redis 启用时跨实例共享计数，否则内存兜底。</p>
     *
     * @param request  登录请求
     * @param httpRequest HTTP 请求（解析客户端 IP）
     * @param response HTTP 响应，用于禁止缓存敏感 Token
     * @return 登录结果
     */
    // 生成 OpenAPI 端点文档，summary/description/operationId 与 openapi-auth.json 的 loginUser 操作对齐。
    @Operation(
            summary = "Login",
            description = "Authenticates credentials and returns a JWT for approved users. "
                    + "Cache-Control: no-store is set on the response. "
                    + "A rate-limited client receives HTTP 429 with code 42905 and Retry-After.",
            operationId = "loginUser")
    // 声明登录接口的错误响应（HTTP 状态 + 业务错误码），与契约 responses 对齐。
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Login successful"),
            @ApiResponse(responseCode = "400", description = "Invalid request parameter (40002)"),
            @ApiResponse(responseCode = "401", description = "Invalid username or password (40001)"),
            @ApiResponse(responseCode = "403", description = "User is not yet approved (40300)"),
            @ApiResponse(responseCode = "429",
                    description = "Login rate limit exceeded (42905). "
                            + "Retry after the number of seconds in Retry-After.")
    })
    @PostMapping("/login")
    public com.susumonitor.server.common.ApiResponse<LoginVo> login(
            @Valid
            @RequestBody LoginRequest request,
            HttpServletRequest httpRequest,
            HttpServletResponse response) {
        LoginRateLimiter limiter = loginRateLimiter.getIfAvailable();
        if (limiter != null) {
            limiter.checkAttempt(clientIpResolver.resolve(httpRequest));
        }
        response.setHeader(HttpHeaders.CACHE_CONTROL, "no-store");
        response.setHeader(HttpHeaders.PRAGMA, "no-cache");
        return com.susumonitor.server.common.ApiResponse.success(userService.login(request));
    }

    /**
     * 返回 Bearer 过滤器从数据库加载的最新安全用户快照。
     *
     * @param authenticatedUser 当前认证用户
     * @return 当前用户信息
     */
    // 生成 OpenAPI 端点文档，summary/description/operationId 与 openapi-auth.json 的 getCurrentUser 操作对齐。
    // 需要 Bearer JWT，声明 security 使 Swagger UI 标记为需要认证。
    @Operation(
            summary = "Current user",
            description = "Returns the latest database snapshot of the authenticated user. "
                    + "The server re-queries the database on every call.",
            operationId = "getCurrentUser",
            security = @SecurityRequirement(name = "bearerAuth"))
    // 声明当前用户接口的错误响应（HTTP 状态 + 业务错误码），与契约 responses 对齐。
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Current user snapshot"),
            @ApiResponse(responseCode = "401", description = "Missing, invalid, or expired JWT (40100)")
    })
    @GetMapping("/me")
    public com.susumonitor.server.common.ApiResponse<CurrentUserVo> me(
            @AuthenticationPrincipal AuthenticatedUser authenticatedUser) {
        return com.susumonitor.server.common.ApiResponse.success(authenticatedUser.toCurrentUserVo());
    }

    /**
     * 登出：Redis 启用时将当前 token 的 jti 写入黑名单（TTL=剩余有效期），
     * 此后任何实例携带该 token 请求均 401（真实失效）；Redis 未启用时保持
     * 无状态空操作（客户端删除本地 JWT，2026-09-14 决策二：文档化接受该语义）。
     * 黑名单写入遇 Redis 故障时按 token-blacklist-on-error 策略分流（见 revokeWithPolicy）。
     *
     * @param request HTTP 请求（读取过滤器放置的 ParsedToken）
     * @return data 为 null 的统一成功响应
     */
    // 生成 OpenAPI 端点文档，summary/description/operationId 与 openapi-auth.json 的 logoutUser 操作对齐。
    // 需要 Bearer JWT，声明 security 使 Swagger UI 标记为需要认证。
    @Operation(
            summary = "Logout",
            description = "Bearer-authenticated logout. When Redis is enabled, the current JWT jti "
                    + "is added to the Redis blacklist with the token's remaining TTL and becomes invalid "
                    + "across instances; when Redis is disabled, logout is a stateless no-op and the client "
                    + "must delete its local JWT. If the blacklist write hits a Redis failure, the response "
                    + "follows susumonitor.security.token-blacklist-on-error: fail_closed (default) returns "
                    + "HTTP 503 with code 50302 and the client should retry; fail_open acknowledges logout "
                    + "and logs a warning (the token stays valid until natural expiry).",
            operationId = "logoutUser",
            security = @SecurityRequirement(name = "bearerAuth"))
    // 声明登出接口的错误响应（HTTP 状态 + 业务错误码），与契约 responses 对齐。
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Logout acknowledged"),
            @ApiResponse(responseCode = "401", description = "Missing, invalid, or expired JWT (40100)"),
            @ApiResponse(responseCode = "503", description = "Redis unavailable while failing closed (50302)")
    })
    @PostMapping("/logout")
    public com.susumonitor.server.common.ApiResponse<Void> logout(HttpServletRequest request) {
        RedisTokenBlacklist blacklist = tokenBlacklist.getIfAvailable();
        if (blacklist != null) {
            JwtTokenService.ParsedToken parsedToken = (JwtTokenService.ParsedToken)
                    request.getAttribute(JwtAuthenticationFilter.JWT_PARSED_TOKEN_ATTRIBUTE);
            if (parsedToken != null) {
                Duration ttl = Duration.between(Instant.now(clock), parsedToken.expiresAt());
                if (!ttl.isNegative() && !ttl.isZero()) {
                    revokeWithPolicy(blacklist, parsedToken.tokenId(), ttl);
                }
            } else {
                log.warn("logout skipped: parsed token missing from request attribute");
            }
        }
        return com.susumonitor.server.common.ApiResponse.success(null);
    }

    /**
     * 按故障语义写入黑名单（2026-09-14 安全评审决策一）。
     *
     * <p>写入成功即完成吊销；Redis 故障时 fail_closed 抛 50302 业务异常（客户端应重试，
     * 否则 Token 未被吊销），fail_open 记 warn 后按登出成功应答（Token 存活至自然过期，
     * 已在契约文档中标注该语义）。</p>
     *
     * @param blacklist Redis 黑名单
     * @param tokenId JWT jti
     * @param ttl 剩余有效期
     */
    private void revokeWithPolicy(RedisTokenBlacklist blacklist, String tokenId, Duration ttl) {
        try {
            blacklist.revoke(tokenId, ttl);
        } catch (org.springframework.dao.DataAccessException exception) {
            if ("fail_open".equals(appProperties.getSecurity().getTokenBlacklistOnError())) {
                log.warn("logout blacklist write failed, failing open; token remains valid until expiry");
                return;
            }
            log.error("logout blacklist write failed, failing closed (token-blacklist-on-error=fail_closed)");
            throw new com.susumonitor.server.common.BusinessException(
                    com.susumonitor.server.common.ErrorCode.REDIS_UNAVAILABLE);
        }
    }
}
